name: PHP tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        php-versions: ['8,2', '8.3', '8.4']

    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v5

      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          tools: composer

      - name: Check PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist

      # https://github.com/marketplace/actions/check-php-syntax-errors
      - name: Check PHP syntax errors
        uses: overtrue/phplint@9

      - name: Coding standards
        run: ./vendor/bin/phpcs

      - name: PHPStan
        run: ./vendor/bin/phpstan

      - name: PHPUnit
        run: ./vendor/bin/phpunit
